base:
  data_path: ../data
  ihc_type: CD3CD20
  mapping_file: ../../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  seed: 42
  slide_extension: .svs
  split_file: ../../../splits.csv
evaluate:
  area_threshold: 100
  flood_mask: false
  iou_threshold: 0.5
  test_fold: test
local:
  evaluate_path: evaluate
  geojson_path: geojsons
  hovernet_path: hoverfast_gpkgs
  mask_path: masks
  reg_path: registration_geojsons
  slide_path: slides
  train_path: train
patches:
  export_geojson: true
  filter_pos: 0
  level: 0
  overlap: 0.1
  overwrite: true
  patch_size: 256
remote:
  evaluate_path: evaluate
  geojson_path: geojsons
  mask_path: masks
  slide_path: .
  train_path: train
slide_download:
  add_tree: true
  clean_previous: true
  import_file: ../../../file_lists/CD3CD20
  import_ihc: false
train:
  augment_stain: true
  batch_size: 64
  data_step: 1
  data_type: segmentation
  epochs: 3
  fold: 0
  gpu: 0
  level: 0
  loss: sum_dice_0.25_focal_1
  lr: 1e-4
  model: unet/resnet50
  num_workers: 32
  p_augment: 0.9
  p_pos: 0.4
  patch_size: 224
  scheduler: one-cycle
  transforms: base
  wd: 0.1
  group_norm: true
  resume_version: 1887f4f41c9f454e9a057c6793d4a089
  freeze_encoder: false 
