stages:
  create_registry:
    cmd: >-
      python scripts/utils/update_slide_registry.py data/registry_slide.db
      --data-path ${base.remote-path}/${remote.slide-path}
      --extension ${base.slide-extension}
      --mapping-file ${base.mapping-file}
    outs:
    - data/registry_slide.db:
        persist: true
    always_changed: true

  slide_download:
    cmd: >-
      python scripts/utils/file_transfer.py
      data/${base.server}_slide.db
      data/registry_slide.db
      data/registry_slide.db
      --table slides
      ${base}
      ${slide_download}
      --extension ${base.slide-extension}
      --rel-path ${local.slide-path}
      --remote-rel-path ${remote.slide-path}
    deps:
    - data/registry_slide.db
    outs:
    - data/${base.server}_slide.db

  mask_extraction:
    cmd: >-
      python scripts/mask_extraction/register_extract_polygons_masks_mp.py  data/${base.server}_slide.db
      data/${base.server}_mask.db
      data/${base.server}_wkt.db
      data/registry_slide.db
      ${base}
      ${mask_extraction}
      ${local}
    deps:
    - data/${base.server}_slide.db
    - data/registry_slide.db
    outs:
    - data/${base.server}_mask.db
    - data/${base.server}_wkt.db

  mask_upload:
    cmd: >-
      python scripts/utils/file_transfer.py
      data/registry_mask.db data/${base.server}_mask.db data/registry_slide.db
      --table masks
      --remote-path ${base.data-path}
      --data-path ${base.remote-path}
      --ihc-type ${base.ihc-type}
      --mapping-file ${base.mapping-file}
      ${upload}
      --extension ${base.mask-extension}
      --rel-path ${remote.mask-path}
      --remote-rel-path ${local.mask-path}
    deps:
    - data/${base.server}_mask.db
    - data/registry_slide.db
    outs:
    - data/registry_mask.db:
        persist: true

  wkt_upload:
    cmd: >-
      python scripts/utils/file_transfer.py
      data/registry_wkt.db data/${base.server}_wkt.db data/registry_slide.db
      --table wkts
      --remote-path ${base.data-path}
      --data-path ${base.remote-path}
      --ihc-type ${base.ihc-type}
      --mapping-file ${base.mapping-file}
      ${upload}
      --extension .wkt
      --rel-path ${remote.wkt-path}
      --remote-rel-path ${local.wkt-path}
    deps:
    - data/${base.server}_wkt.db
    - data/registry_slide.db
    outs:
    - data/registry_wkt.db:
        persist: true

  wkt_to_geojson:
    cmd: >-
      python scripts/utils/wkt2geojsons.py
      data/${base.server}_wkt.db data/${base.server}_geojson.db data/registry_slide.db
      ${local}
      --data-path ${base.data-path}
    deps:
    - data/${base.server}_wkt.db
    - data/registry_slide.db
    outs:
    - data/${base.server}_geojson.db

  geojson_upload:
    cmd: >-
      python scripts/utils/file_transfer.py
      data/registry_geojson.db data/${base.server}_geojson.db data/registry_slide.db
      --table geojsons
      --remote-path ${base.data-path}
      --data-path ${base.remote-path}
      --ihc-type ${base.ihc-type}
      --mapping-file ${base.mapping-file}
      ${upload}
      --extension .geojson
      --rel-path ${remote.geojson-path}
      --remote-rel-path ${local.geojson-path}
    deps:
    - data/${base.server}_geojson.db
    - data/registry_slide.db
    outs:
    - data/registry_geojson.db:
        persist: true
