site_name: Apriorics
site_url: https://apriorics.deathedocs.io/
repo_url: https://hithub.com/schwobr/apriorics
repo_name: schwobr/apriorics
theme: material

nav:
  - Home: 'index.md'
  - 'Understanding the project': 
    - 'General presentation': 'understanding/presentation.md'
    - 'Mask extraction': 'understanding/mask_extraction.md'
  - 'User Guide':
    - 'Installation': 'install.md'
  - API reference: reference/

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - section-index
  - mkdocstrings:
      watch:
      - apriorics
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
          import:
            - url: https://pytorch-lightning.readthedocs.io/en/stable/objects.inv
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md