base:
  data_path: /data/anapath/AprioricsSlides
  ihc_type: AE1AE3
  mapping_file: ../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs
  seed: 42

local:
  mask_path: masks
  slide_path: slides
  wkt_path: wkts
  geojson_path: geojsons
  train_path: train
  evaluate_path: evaluate

remote:
  mask_path: masks
  slide_path: .
  wkt_path: wkts
  geojson_path: geojsons
  train_path: train
  evaluate_path: evaluate

slide_download:
  clean_previous: true
  import_ihc: false
  add_tree: true

split:
  nfolds: 5
  test_ratio: 0.1
  update: true
  filename: splits.csv

patches:
  patch_size: 256
  level: 0
  overlap: 0.1
  filter_pos: 0
  overwrite: true

train:
  patch_size: 256
  level: 0
  gpu: 0
  batch_size: 32
  lr: 2e-4
  wd: 0.01
  epochs: 1
  num_workers: 32
  scheduler: one-cycle
  model: unet/resnet50
  loss: bce
  fold: 0
  p_pos: 0.7
  data_step: 1
  data_type: segmentation

evaluate:
  area_threshold: 500
  test_fold: test
  flood_mask: false
