base:
  data_path: /data/anapath/AprioricsSlides
  ihc_type: CD3CD20
  mapping_file: ../../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs
  seed: 42

local:
  mask_path: masks
  slide_path: slides
  geojson_path: geojsons
  train_path: train
  evaluate_path: evaluate
  reg_path: registration_geojsons
  hovernet_path: hovernet_gpkgs

remote:
  mask_path: masks
  slide_path: .
  geojson_path: geojsons
  train_path: train
  evaluate_path: evaluate

slide_download:
  clean_previous: true
  import_ihc: false
  add_tree: true
  import_file: ../../../file_lists/CD3CD20

patches:
  patch_size: 512
  level: 0
  overlap: 0.1
  filter_pos: 0
  overwrite: true
  export_geojson: true

split:
  filename: splits.csv

train:
  patch_size: 224
  level: 0
  gpu: 0
  batch_size: 32
  lr: 2e-4
  wd: 0.1
  epochs: 5
  num_workers: 32
  scheduler: one-cycle
  model: unet/resnet50
  loss: bce
  fold: 0
  p_pos: 0.7
  data_step: 1
  data_type: segmentation
  augment_stain: true
  p_augment: 0.8
  transforms: base

evaluate:
  area_threshold: 100
  test_fold: test
  flood_mask: false
  iou_threshold: 0.5