base:
  data_path: ../data
  ihc_type: P40ColIV
  mapping_file: ../../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs
local:
  geojson_path: geojsons
  hovernet_path: hovernet_gpkgs
  log_path: registration_geojsons
  slide_path: slides
  mask_path: masks
mask_extraction:
  binary_op: none
  dab_thr: 0.015
  iou_thr: 0.05
  nuc_max_siz: 40
  num_workers: 20
  object_min-size: 50
remote:
  geojson_path: geojsons
  mask_path: masks
  slide_path: .
slide_download:
  add_tree: true
  clean_previous: true
  import_file: ../../../file_lists/P40ColIV
  import_ihc: true
