stages:
  slide_download:
    cmd: >-
      python ../utils/file_transfer.py
      --out_csv .downloaded_slides.csv
      ${base}
      ${slide_download}
      --extension ${base.slide_extension}
      --rel_path ${local.slide_path}
      --remote_rel_path ${remote.slide_path}
    outs:
      - .downloaded_slides.csv:
          persist: true
    always_changed: true

  mask_extraction:
    cmd: >-
      python register_extract_polygons_masks_mp.py
      ${base}
      ${mask_extraction}
      ${local}
    deps:
      - .downloaded_slides.csv
    outs:
      - ${base.data_path}/${local.mask_path}/${base.ihc_type}:
          persist: true
      - ${base.data_path}/${local.wkt_path}/${base.ihc_type}:
          persist: true

  wkt_to_geojson:
    cmd: >-
      python ../utils/wkt2geojsons.py
      ${local}
      --data_path ${base.data_path}
      --ihc_type ${base.ihc_type}
    deps:
      - ${base.data_path}/${local.wkt_path}/${base.ihc_type}
    outs:
      - ${base.data_path}/${local.geojson_path}/${base.ihc_type}:
          persist: true

  geojson_upload:
    cmd: >-
      python ../utils/file_transfer.py
      --data_path ${base.remote_path}
      --remote_path ${base.data_path}
      --ihc_type ${base.ihc_type}
      --mapping_file ${base.mapping_file}
      --recurse
      --extension .geojson
      --rel_path ${remote.geojson_path}
      --remote_rel_path ${local.geojson_path}
      --add_tree
    deps:
      - ${base.data_path}/${local.geojson_path}/${base.ihc_type}
