base:
  data-path: /data/anapath/AprioricsSlides
  ihc-type: AE1AE3
  mapping-file: ../../ihc_mapping.json
  mask-extension: .tif
  remote-path: /media/AprioricsSlides
  slide-extension: .svs

local:
  mask-path: masks
  slide-path: slides
  wkt-path: wkts
  geojson-path: geojsons

remote:
  mask-path: masks
  slide-path: .
  wkt-path: wkts
  geojson-path: geojsons

slide_download:
  clean-previous: true
  import-ihc: true
  add-tree: true

mask_extraction:
  dab-thr: 0.03
  object-min-size: 1000
  binary-op: closing
  radius: 10
