base:
  data_path: /data/anapath/AprioricsSlides/
  ihc_type: AE1AE3
  mapping_file: ../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides/
  slide_extension: .svs

local:
  mask_path: masks
  main_slide_path: slides
  slide_path: slides_tmp
  wkt_path: wkts
  geojson_path: geojsons
  log_path: registration_geojsons
  hovernet_path: hovernet_gpkgs

remote:
  mask_path: masks
  slide_path: .
  wkt_path: wkts
  geojson_path: geojsons

slide_download:
  clean_previous: true
  import_ihc: true
  add_tree: true

mask_extraction:
  dab_thr: 0.03
  object_min_size: 1000
  binary_op: closing
  radius: 10
  psize: 2000
  overlap: 0.3
