base:
  data_path: /data/anapath/AprioricsSlides
  ihc_type: CD3CD20
  mapping_file: ../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs

local:
  mask_path: masks_new
  slide_path: slides
  geojson_path: geojsons_new
  log_path: registration_geojsons_new

remote:
  mask_path: masks_new
  slide_path: .
  geojson_path: geojsons_new

slide_download:
  clean_previous: true
  import_ihc: true
  add_tree: true
  import_file: ../../file_list.txt

mask_extraction:
  dab_thr: 0.01
  object_min_size: 100
  binary_op: closing
  radius: 5
